### ISSUE TITLE
EmbeddedColorWell

### ISSUE THREAD

**Issue by bill1m** [trozware/swiftui-mac#1]
[EmbeddedColorWell.txt](https://github.com/trozware/swiftui-mac/files/4100919/EmbeddedColorWell.txt)
Thanks for the articles and code examples!  It has helped me immensely.

I noticed that the selectedColor in the EmbeddedColorWell is not being mutated and is not being used in a two-way manner.  The selectedColor is initialized to NSColor.blue and used to set the color in the NSColorWell view.  When the NSColorWell color is changed, it does change the color of the EmbeddedColorWell view.  However, the actual @State var selectedColor value is never mutated in this process beyond the initialized value of NSColor.blue.  

To see this, add the .background modifier to the Text as shown below:

`            HStack {
                Text("Choose a color:")
                  .background(Color(selectedColor))
                EmbeddedColorWell(selectedColor: $selectedColor)
                    .frame(width: 44, height: 23)
            }`

When the color is chosen in the NSColorWell, the background color does not change.

Attached is a modified version of the EmbeddedColorWell that will alter the value of selectedColor when the NSColorWell.color changes.

**Comment by trozware** [comment]
Thanks for this Bill. Very good to know and thanks for providing the full solution.

I will add this new info into an upcoming update to these articles.

Regards,
Sarah,

Sarah Reichelt
sarah@troz.net

https://troz.net

@trozware

**Comment by bill1m** [comment]
Hi Sarah,

Thank you!

BTW: 

            if self.embedded.selectedColor != color {
              self.embedded.selectedColor = color
            }

I think this can be reduced to a simple assignment.  An earlier version was firing on all sorts of view changes.

B~

**Comment by trozware** [comment]
Thanks Bill, I have published your modifications in an addition to the original articles at https://troz.net/post/2020/swiftui_for-mac-extras/
